import BaseCalendar from '@/components/calendar/base/BaseCalendar';
import BaseLayout from '@/components/layout/base/BaseLayout';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import BackofficeService from 'src/services/BackofficeService';
import IJobData from 'src/types/job.type';
import IUserData from 'src/types/user.type';

export default function Home() {
  const router = useRouter();
  const [techs, setTechs] = useState<IUserData[]>([]);
  const [jobs, setJobs] = useState<IJobData[]>([]);

  const fetchTechnicians = async () => {
    let res: any;
    res = await BackofficeService.fetchAllUsers();
    setTechs(res.data.data);
    res.data.data.map((item: IUserData) => {
      techs.push(item)
    });
  };
  const fetchJobs = async () => {
    let res: any;
    res = await BackofficeService.fetchAllJobs();
    setJobs(res.data.data);
    res.data.data.map((item: IJobData) => {
      jobs.push(item);
    });
  };

  useEffect(() => {
      fetchTechnicians();
      fetchJobs();
    
  }, []);
 

  return (
    <>
      <Head>
        <title>Backoffice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BaseLayout router={router}>
          <BaseCalendar
          technicians={techs}
          interventions={jobs}
           sampleTextProp="test" />
        </BaseLayout>
      </main>
    </>
  );
}
